AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: lambda function for h-scraper
Parameters:
  ApplicationName:
    Type: String
    Default: h-webscraper
    Description: Name of the lambda function
  Environment:
    Type: String
    Description: Environment tag that helps build the Environment
  S3BucketName:
    Type: String
    Description: Bucket where the source code is located
  BuildId:
    Type: Number
    Description: BuildId from the codebuild end run-time environment variable
  LambdaHandler:
    Description: The Python handler for the Lambda function
    Type: String
    Default: handler.hello
  LambdaMemorySize:
    Description: Memory size for the lambda function
    Type: Number
    Default: 256
  LambdaTimeout:
    Description: Timeout length for the lambda function
    Type: Number
    Default: 900
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn: MyLambdaPolicy
    Properties:
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key:
          Fn::Join:
            - ""
            - - "lambda/"
              - !Ref ApplicationName
              - "/"
              - !Ref Environment
              - "/"
              - !Ref ApplicationName
              - "-"
              - !Ref Environment
              - "-"
              - !Ref BuildId
              - ".zip"
      Handler:
        Ref: LambdaHandler
      MemorySize:
        Ref: LambdaMemorySize
      Runtime: python3.7
      Role:
        Fn::GetAtt:
          - MyLambdaRole
          - Arn
      Timeout:
        Ref: LambdaTimeout
        
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
  MyLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyLambdaPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListAllMyBuckets
              - s3:ListBucket
              - s3:PutBucketPolicy
            Resource:
              - !Sub arn:aws:s3:::${S3BucketName}
              - !Sub arn:aws:s3:::${S3BucketName}/*
      Roles:
        - Ref: MyLambdaRole
