AWSTemplateFormatVersion: '2010-09-09'

Transform: AWS::Serverless-2016-10-31
Description: Sets up the serverless function for zillow-webscraper
Resources:
  helloworlddev:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.handler
      Runtime: python3.8
      CodeUri: ./
      Policies: 
        - S3FullAccessPolicy