AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Sets up the serverless function for zillow-webscraper

Parameters:
  DeploymentBucket:
    Type: String
    Default: zillow-webscraper
    Description: Bucket where the files will be deployed.
  BuildArtifactsBucket:
    Type: String
    Default: zillow-webscraper-build-artifacts
    Description: S3 Bucket used for storing code artifacts.
Resources:

  HelloWorld:
    Type: AWS::Serverless::Function
    DependsOn: MyLambdaPolicy
    Properties:
      CodeUri: ./build
      Handler: handler.hello
      Runtime: python3.8
      Role: !GetAtt MyLambdaRole.Arn

  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole

  MyLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: MyLambdaPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:GetBucketPolicy
              - s3:GetObject
              - s3:ListAllMyBuckets
              - s3:ListBucket
              - s3:PutBucketPolicy
            Resource:
              - arn:aws:s3:::zillow-webscraper
              - arn:aws:s3:::zillow-webscraper/*
      Roles:
        - Ref: MyLambdaRole

